app:
  enable_wandb: false
  ip: 127.0.0.1
  port: 6009

model:
  data_device: cuda
  source_path: ./input_scene/llff/flower
  model_path: ./input_gaussian/llff/flower

style:
  exec_mode: sematic
  style_images: ["./input_styles/32.jpg"]

  scene_prompt: ["flower"]
  style_prompt: ["bull"]
  override_matches: [1, 0]

  enable_erode: true
  enable_isolate: true

  enable_color_transfer: true
  method: fast

  stylized_model_path: output/flower_32_sematic
  
  iterations_pre_process: 400
  iterations_stylize: 600
  iterations_post_process: 400
